CREATE TABLE `t_admin` (
  `ADMIN_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '业务ID',
  `ADMIN_NAME` varchar(20) DEFAULT NULL COMMENT '管理员账号',
  `SEX` int(11) DEFAULT NULL COMMENT '性别 1-男，2-女 ',
  `EMAIL` varchar(32) DEFAULT NULL COMMENT '邮箱',
  `PASSWORD` varchar(32) DEFAULT NULL COMMENT '密码',
  `NICKNAME` varchar(50) DEFAULT NULL COMMENT '昵称',
  `STATUS` int(11) DEFAULT NULL COMMENT '状态 0-禁用，1-启用',
  `CREATE_BY` varchar(20) DEFAULT NULL COMMENT '创建人ID',
  `CREATE_BY_NAME` varchar(20) DEFAULT NULL COMMENT '创建人名称',
  `CREATE_TIME` date DEFAULT NULL COMMENT '创建时间',
  `LAST_UPDATE_BY` varchar(20) DEFAULT NULL COMMENT '最后修改人ID',
  `LAST_UPDATE_NAME` varchar(20) DEFAULT NULL COMMENT '最后修改人名称',
  `LAST_UPDATE_TIME` date DEFAULT NULL COMMENT '最后修改时间',
  PRIMARY KEY (`ADMIN_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10060 DEFAULT CHARSET=utf8 COMMENT='管理员账号表';


INSERT INTO `t_admin` VALUES (10000, 'admin', 1, 'iChanl@iChanl.com', 'E10ADC3949BA59ABBE56E057F20F883E', '超级管理员', 1, '10000', 'super', '2017-1-11', '10000', 'super', '2017-2-21');
